### ISSUE TITLE
No discoverable link for Manage This Entry

### ISSUE THREAD

**Issue by larryhastings** [pyweekorg/pyweekorg#24]
I am a member of team "wasabi26".  The main landing page for our entry:
  https://pyweek.org/e/wasabi26/
doesn't display a "Manage This Entry" link, even when I am logged in.

The "Manage This Entry" page:
  https://pyweek.org/e/wasabi26/manage/
**does** display a "Manage This Entry" link, in the header bar ("Home", "Add Diary Entry", etc).  I'm guessing the header bar on the main landing page for our entry is meant to display "Manage This Entry" when you're logged in... but doesn't.

**Comment by rdb** [comment]
I can verify that this is a problem for me as well.  It might be that this only occurs for teams on which you are a member, but not the creator.

**Comment by lordmauve** [comment]
I think it was intended that only the team leader can "manage this entry". I don't know what the reasoning behind that was.

**Comment by rdb** [comment]
But the Manage link does show up on other pages.  If I go to Upload, the Manage link pops up in the menu, just not on the main page.  So the logic is being applied inconsistently.

I would posit that any member should be able to edit the description.
