### ISSUE TITLE
"Your Latest Entries" menu shows previous PyWeek entry

### ISSUE THREAD

**Issue by rdb** [pyweekorg/pyweekorg#43]
We're in the upload period for PyWeek 28, but the dropdown menu on the top-right suddenly shows my entry for PyWeek 27:

![image](https://user-images.githubusercontent.com/194842/65823886-0da1f880-e25f-11e9-896b-fd8a2bbcf593.png)

**Comment by lordmauve** [comment]
Yes, I saw that too. It shows your previous entry regardless of whether you have uploaded or not.

**Comment by rdb** [comment]
This appears to be due to c3508cc47d3566ecedcc60e343b56e3b2033aff8 adding a check for `isRegoOpen()` and of course my changes which changed the meaning of `isRegoOpen()` a bit; I will create a PR fixing this.
